imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*, build/*, database/*]

build:
  nodes:
    coverage:
      tests:
        override:
          - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover build/clover.xml
            coverage:
              file: build/clover.xml   # <- Set this to where we find the coverage data.
                                          #    The path is relative to the current directory.
              format: clover
