language: php

php:
  - '7.4'

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-xml build
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text build
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-html build
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover build/clover.xml
